### ISSUE TITLE
"hideSearch = false" Breaks Mobile Navigation Header

### ISSUE THREAD

**Issue by Aaron-Rhoades** [ny/universal-navigation#213]
In order to hide the "search" bar, we are instructed to set the "hideSearch" variable to "false". This works properly in the full width site, but it glitches the Universal Navigation on mobile. You cannot see the Universal Navigation at all, unfortunately. 

After an "Inspect Element" investigation, I've found that if you remove the "nygov-hide-search" class from the <html> element then it fixes itself (but the search bar shows, of course).

**Comment by Aaron-Rhoades** [comment]
I am able to temporarily solve the problem with the following:
   '@media(max-width:767px){
	.nygov-hide-search header#nygov-header {
	    top: 76px;
	}
}'
I've found that the problem is, due to the search bar being gone, the `header#nygov-header` element falls above visibility.

**Comment by Aaron-Rhoades** [comment]
Also be advised that after applying my above fix, then the navigation opened too far. Odd. My updated temporary fix is as follows:
##Updated Temporary Fix
````css
@media(max-width:767px){/*THIS FIXES THE UNIVERSAL NAVIGATION DISAPPEARING*/
	.nygov-hide-search header#nygov-header {
	    top: 76px; /* corrects the "top" position to display the closed nav */
	}
	.nygov-hide-search header#nygov-header.nav-open {
	    top:0; /* sets it back to how it was, so it isn't "opened too far" */
	}
}
````
